---
# Source: ceph-osd/templates/daemonset-osd.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name
  namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-release-name
  namespace: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-ceph-release-name
subjects:
  - kind: ServiceAccount
    name: release-name
    namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-ceph-release-name
  namespace: ceph
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods

  

  

  

  

    
    
    

    

    

    

    

    
---
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ceph-osd-default
data:
  ceph.conf: |
    [global]
    cephx = true
    cephx_cluster_require_signatures = true
    cephx_require_signatures = false
    cephx_service_require_signatures = false
    debug_ms = 0/0
    fsid = 4f2e3b63-280a-4c42-a75e-0072646c0eab
    mon_host = ceph-mon.ceph.svc.cluster.local:3300
    mon_osd_down_out_interval = 1800
    mon_osd_down_out_subtree_limit = root
    mon_osd_min_in_ratio = 0
    mon_osd_min_up_ratio = 0
    objecter_inflight_op_bytes = 1073741824
    objecter_inflight_ops = 10240
    [osd]
    cluster_network = 20.0.0.0/24
    filestore_max_sync_interval = 10
    filestore_merge_threshold = -10
    filestore_split_multiple = 12
    ms_bind_port_max = 7100
    ms_bind_port_min = 6800
    osd_crush_update_on_start = false
    osd_deep_scrub_stride = 1048576
    osd_journal_size = 10240
    osd_max_object_name_len = 256
    osd_mkfs_options_xfs = -f -i size=2048
    osd_mkfs_type = xfs
    osd_mount_options_xfs = rw,noatime,largeio,inode64,swalloc,logbufs=8,logbsize=256k,allocsize=4M
    osd_pg_max_concurrent_snap_trims = 1
    osd_recovery_max_active = 1
    osd_recovery_op_priority = 1
    osd_scrub_begin_hour = 22
    osd_scrub_chunk_max = 4
    osd_scrub_chunk_min = 1
    osd_scrub_during_recovery = false
    osd_scrub_end_hour = 4
    osd_scrub_load_threshold = 10
    osd_scrub_priority = 1
    osd_scrub_sleep = 0.1
    osd_snap_trim_priority = 1
    osd_snap_trim_sleep = 0.1
    public_network = 20.0.0.0/24
    [target]
    required_percent_of_osds = 75
    
  storage.json: |
    {
      "failure_domain": "host",
      "failure_domain_by_hostname": "false",
      "failure_domain_name": "false",
      "osd": [
        {
          "data": {
            "location": "/var/lib/openstack-helm/ceph/osd/osd-one",
            "type": "directory"
          },
          "journal": {
            "location": "/var/lib/openstack-helm/ceph/osd/journal-one",
            "type": "directory"
          }
        }
      ]
    }

    

---






  
    
    
  
  
    
    
  
  
    
    
    
  
    
    
    
  
    
    
    
  
    
    
    
  
    
    
    
  
    
    
    
  

apiVersion: apps/v1
kind: DaemonSet
metadata:
  annotations:
    openstackhelm.openstack.org/release_uuid: ""
  labels:
    application: ceph
    component: osd
    release_group: release-name
  name: ceph-osd-default-83945928
spec:
  minReadySeconds: 0
  selector:
    matchLabels:
      application: ceph
      component: osd
      release_group: release-name
  template:
    metadata:
      annotations:
        configmap-bin-hash: 61f335fd3008b49260670c4949dd8f674c1c3aaec1c9ed6f4ff9deaf257f96e0
        configmap-etc-hash: 7c7714e17878d14f2156ca238b7e2e80bd60092956c2fabb671591b7a32eef31
        container.apparmor.security.beta.kubernetes.io/ceph-init-dirs: runtime/default
        container.apparmor.security.beta.kubernetes.io/ceph-log-ownership: runtime/default
        container.apparmor.security.beta.kubernetes.io/ceph-osd-default: runtime/default
        container.apparmor.security.beta.kubernetes.io/init: runtime/default
        container.apparmor.security.beta.kubernetes.io/osd-init: runtime/default
        openstackhelm.openstack.org/release_uuid: ""
      labels:
        application: ceph
        component: osd
        release_group: release-name
    spec:
      containers:
      - command:
        - /tmp/log-tail.sh
        env:
        - name: JOURNAL_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/journal-one
        - name: STORAGE_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/osd-one
        - name: JOURNAL_TYPE
          value: directory
        - name: STORAGE_TYPE
          value: directory
        - name: DAEMON_NAME
          value: ceph-osd
        - name: TRUNCATE_SIZE
          value: "0"
        - name: TRUNCATE_PERIOD
          value: "3600"
        - name: WAIT_FOR_OSD_ID_TIMEOUT
          value: "300"
        image: docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416
        imagePullPolicy: IfNotPresent
        name: log-runner
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /tmp
          name: pod-tmp
        - mountPath: /tmp/log-tail.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: log-tail.sh
        - mountPath: /var/log/ceph
          name: pod-var-log
          readOnly: false
      - command:
        - /tmp/osd-start.sh
        env:
        - name: JOURNAL_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/journal-one
        - name: STORAGE_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/osd-one
        - name: JOURNAL_TYPE
          value: directory
        - name: STORAGE_TYPE
          value: directory
        - name: CLUSTER
          value: ceph
        - name: DEPLOY_TOOL
          value: ceph-disk
        - name: CEPH_GET_ADMIN_KEY
          value: "1"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MON_PORT
          value: "6789"
        - name: MON_PORT_V2
          value: "3300"
        image: docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416
        imagePullPolicy: IfNotPresent
        lifecycle:
          preStop:
            exec:
              command:
              - /tmp/osd-stop.sh
        livenessProbe:
          exec:
            command:
            - /tmp/osd-check.sh
            - liveness
          initialDelaySeconds: 120
          periodSeconds: 60
        name: ceph-osd-default
        readinessProbe:
          exec:
            command:
            - /tmp/osd-check.sh
            - readiness
          initialDelaySeconds: 60
          periodSeconds: 60
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /tmp
          name: pod-tmp
        - mountPath: /run
          name: pod-run
        - mountPath: /etc/ceph
          name: pod-etc-ceph
        - mountPath: /etc/forego
          name: pod-forego
        - mountPath: /tmp/osd-start.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-start.sh
        - mountPath: /tmp/osd-directory-ceph-disk.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-directory-ceph-disk.sh
        - mountPath: /tmp/osd-block-ceph-disk.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-block-ceph-disk.sh
        - mountPath: /tmp/osd-block-ceph-volume.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-block-ceph-volume.sh
        - mountPath: /tmp/osd-bluestore-ceph-disk.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-bluestore-ceph-disk.sh
        - mountPath: /tmp/osd-bluestore-ceph-volume.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-bluestore-ceph-volume.sh
        - mountPath: /tmp/osd-check.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-check.sh
        - mountPath: /tmp/osd-stop.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-stop.sh
        - mountPath: /tmp/utils-checkDNS.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: utils-checkDNS.sh
        - mountPath: /tmp/osd-common-ceph-disk.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-common-ceph-disk.sh
        - mountPath: /tmp/osd-common-ceph-volume.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-common-ceph-volume.sh
        - mountPath: /tmp/utils-defragOSDs.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: utils-defragOSDs.sh
        - mountPath: /etc/ceph/storage.json
          name: ceph-osd-etc
          readOnly: true
          subPath: storage.json
        - mountPath: /etc/ceph/ceph.conf.template
          name: ceph-osd-etc
          readOnly: true
          subPath: ceph.conf
        - mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
          name: ceph-bootstrap-osd-keyring
          readOnly: false
          subPath: ceph.keyring
        - mountPath: /dev
          name: devices
          readOnly: false
        - mountPath: /var/lib/ceph
          name: pod-var-lib-ceph
          readOnly: false
        - mountPath: /run/lvm
          name: run-lvm
          readOnly: false
        - mountPath: /run/udev
          name: run-udev
          readOnly: false
        - mountPath: /etc/lvm
          name: pod-etc-lvm
          readOnly: false
        - mountPath: /var/lib/ceph/osd
          name: data
          readOnly: false
        - mountPath: /var/lib/ceph/journal
          name: journal
          readOnly: false
        - mountPath: /var/log/ceph
          name: pod-var-log
          readOnly: false
      dnsPolicy: ClusterFirstWithHostNet
      hostIPC: true
      hostNetwork: true
      hostPID: true
      initContainers:
      - command:
        - kubernetes-entrypoint
        env:
        - name: JOURNAL_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/journal-one
        - name: STORAGE_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/osd-one
        - name: JOURNAL_TYPE
          value: directory
        - name: STORAGE_TYPE
          value: directory
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INTERFACE_NAME
          value: eth0
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
        - name: DEPENDENCY_SERVICE
          value: ceph:ceph-mon
        - name: DEPENDENCY_JOBS
          value: ceph-storage-keys-generator,ceph-osd-keyring-generator
        - name: DEPENDENCY_DAEMONSET
          value: ""
        - name: DEPENDENCY_CONTAINER
          value: ""
        - name: DEPENDENCY_POD_JSON
          value: ""
        - name: DEPENDENCY_CUSTOM_RESOURCE
          value: ""
        image: quay.io/airshipit/kubernetes-entrypoint:v1.0.0
        imagePullPolicy: IfNotPresent
        name: init
        securityContext:
          allowPrivilegeEscalation: false
          readOnlyRootFilesystem: true
          runAsUser: 65534
        volumeMounts: []
      - command:
        - /tmp/init-dirs.sh
        env:
        - name: JOURNAL_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/journal-one
        - name: STORAGE_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/osd-one
        - name: JOURNAL_TYPE
          value: directory
        - name: STORAGE_TYPE
          value: directory
        - name: CLUSTER
          value: ceph
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MON_PORT
          value: "6789"
        - name: MON_PORT_V2
          value: "3300"
        image: docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416
        imagePullPolicy: IfNotPresent
        name: ceph-init-dirs
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /tmp
          name: pod-tmp
        - mountPath: /run
          name: pod-run
        - mountPath: /etc/ceph
          name: pod-etc-ceph
        - mountPath: /tmp/init-dirs.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: init-dirs.sh
        - mountPath: /etc/ceph/storage.json
          name: ceph-osd-etc
          readOnly: true
          subPath: storage.json
        - mountPath: /var/lib/ceph
          name: pod-var-lib-ceph
          readOnly: false
        - mountPath: /var/lib/ceph/tmp
          name: pod-var-lib-ceph-tmp
          readOnly: false
      - command:
        - chown
        - -R
        - ceph:root
        - /var/log/ceph
        env:
        - name: JOURNAL_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/journal-one
        - name: STORAGE_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/osd-one
        - name: JOURNAL_TYPE
          value: directory
        - name: STORAGE_TYPE
          value: directory
        - name: CLUSTER
          value: ceph
        - name: CEPH_GET_ADMIN_KEY
          value: "1"
        image: docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416
        imagePullPolicy: IfNotPresent
        name: ceph-log-ownership
        securityContext:
          readOnlyRootFilesystem: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /tmp
          name: pod-tmp
        - mountPath: /run
          name: pod-run
        - mountPath: /etc/ceph
          name: pod-etc-ceph
        - mountPath: /var/log/ceph
          name: pod-var-log
          readOnly: false
      - command:
        - /tmp/osd-init.sh
        env:
        - name: JOURNAL_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/journal-one
        - name: STORAGE_LOCATION
          value: /var/lib/openstack-helm/ceph/osd/osd-one
        - name: JOURNAL_TYPE
          value: directory
        - name: STORAGE_TYPE
          value: directory
        - name: CLUSTER
          value: ceph
        - name: DEPLOY_TOOL
          value: ceph-disk
        - name: CEPH_GET_ADMIN_KEY
          value: "1"
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: MON_PORT
          value: "6789"
        - name: MON_PORT_V2
          value: "3300"
        image: docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416
        imagePullPolicy: IfNotPresent
        name: osd-init
        securityContext:
          privileged: true
          readOnlyRootFilesystem: true
          runAsUser: 0
        volumeMounts:
        - mountPath: /tmp
          name: pod-tmp
        - mountPath: /run
          name: pod-run
        - mountPath: /etc/ceph
          name: pod-etc-ceph
        - mountPath: /tmp/osd-init.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-init.sh
        - mountPath: /tmp/init-ceph-disk.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-init-ceph-disk.sh
        - mountPath: /tmp/init-ceph-volume.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-init-ceph-volume.sh
        - mountPath: /tmp/osd-common-ceph-disk.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-common-ceph-disk.sh
        - mountPath: /tmp/osd-common-ceph-volume.sh
          name: ceph-osd-bin
          readOnly: true
          subPath: osd-common-ceph-volume.sh
        - mountPath: /etc/ceph/ceph.conf.template
          name: ceph-osd-etc
          readOnly: true
          subPath: ceph.conf
        - mountPath: /etc/ceph/storage.json
          name: ceph-osd-etc
          readOnly: true
          subPath: storage.json
        - mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
          name: ceph-bootstrap-osd-keyring
          readOnly: false
          subPath: ceph.keyring
        - mountPath: /dev
          name: devices
          readOnly: false
        - mountPath: /var/lib/ceph
          name: pod-var-lib-ceph
          readOnly: false
        - mountPath: /var/lib/ceph/tmp
          name: pod-var-lib-ceph-tmp
          readOnly: false
        - mountPath: /run/lvm
          name: run-lvm
          readOnly: false
        - mountPath: /run/udev
          name: run-udev
          readOnly: false
        - mountPath: /etc/lvm
          name: pod-etc-lvm
          readOnly: false
        - mountPath: /var/lib/ceph/osd
          name: data
          readOnly: false
        - mountPath: /var/lib/ceph/journal
          name: journal
          readOnly: false
        - mountPath: /var/log/ceph
          name: pod-var-log
          readOnly: false
      nodeSelector:
        ceph-osd: enabled
      securityContext:
        runAsUser: 65534
      serviceAccountName: release-name
      volumes:
      - emptyDir: {}
        name: pod-tmp
      - emptyDir:
          medium: Memory
        name: pod-run
      - emptyDir: {}
        name: pod-etc-ceph
      - emptyDir: {}
        name: pod-forego
      - hostPath:
          path: /dev
        name: devices
      - hostPath:
          path: /run/lvm
        name: run-lvm
      - hostPath:
          path: /run/udev
        name: run-udev
      - emptyDir: {}
        name: pod-etc-lvm
      - emptyDir: {}
        name: pod-var-lib-ceph
      - hostPath:
          path: /var/lib/openstack-helm/ceph/var-tmp
          type: DirectoryOrCreate
        name: pod-var-lib-ceph-tmp
      - emptyDir: {}
        name: pod-var-log
      - configMap:
          defaultMode: 365
          name: release-name-bin
        name: ceph-osd-bin
      - configMap:
          defaultMode: 292
          name: ceph-osd-default
        name: ceph-osd-etc
      - name: ceph-bootstrap-osd-keyring
        secret:
          secretName: ceph-bootstrap-osd-keyring
      - hostPath:
          path: /var/lib/openstack-helm/ceph/osd/osd-one
        name: data
      - hostPath:
          path: /var/lib/openstack-helm/ceph/osd/journal-one
        name: journal
  updateStrategy:
    rollingUpdate:
      maxUnavailable: 1
    type: RollingUpdate




---
