---
# Source: horizon/templates/pdb.yaml

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: horizon
spec:
  minAvailable: 0
  selector:
    matchLabels:
      release_group: release-name
      application: horizon
      component: server
