---
# Source: horizon/templates/pod-helm-tests.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-test
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-release-name-test
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-openstack-release-name-test
subjects:
  - kind: ServiceAccount
    name: release-name-test
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-openstack-release-name-test
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
---
apiVersion: v1
kind: Pod
metadata:
  name: release-name-test
  labels:
    release_group: release-name
    application: horizon
    component: test
  annotations:
    "helm.sh/hook": test-success
    "openstackhelm.openstack.org/release_uuid": ""
spec:
  restartPolicy: Never
  serviceAccountName: release-name-test
  nodeSelector:
    openstack-control-plane: enabled
  initContainers:
    
    - name: init
      image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
      imagePullPolicy: IfNotPresent  
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsUser: 65534
        
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INTERFACE_NAME
          value: eth0
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
        - name: DEPENDENCY_SERVICE
          value: "openstack:horizon-int"
        - name: DEPENDENCY_DAEMONSET
          value: ""
        - name: DEPENDENCY_CONTAINER
          value: ""
        - name: DEPENDENCY_POD_JSON
          value: ""
        - name: DEPENDENCY_CUSTOM_RESOURCE
          value: ""
      command:
        - kubernetes-entrypoint
      volumeMounts:
        null
        
  containers:
    - name: release-name-test
      image: "docker.io/openstackhelm/osh-selenium:latest-ubuntu_bionic"
      imagePullPolicy: IfNotPresent
      
      command:
        - /tmp/selenium-test.py
      env:        
        - name: OS_IDENTITY_API_VERSION
          value: "3"
        - name: OS_AUTH_URL
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_AUTH_URL
        - name: OS_REGION_NAME
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_REGION_NAME
        - name: OS_INTERFACE
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_INTERFACE
        - name: OS_PROJECT_DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_PROJECT_DOMAIN_NAME
        - name: OS_PROJECT_NAME
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_PROJECT_NAME
        - name: OS_USER_DOMAIN_NAME
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_USER_DOMAIN_NAME
        - name: OS_USERNAME
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_USERNAME
        - name: OS_PASSWORD
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_PASSWORD
        - name: OS_DEFAULT_DOMAIN
          valueFrom:
            secretKeyRef:
              name: horizon-keystone-admin
              key: OS_DEFAULT_DOMAIN
        - name: HORIZON_URI
          value: http://horizon.openstack.svc.cluster.local/
      volumeMounts:
        - name: pod-tmp
          mountPath: /tmp
        - name: horizon-bin
          mountPath: /tmp/selenium-test.py
          subPath: selenium-test.py
          readOnly: true

  volumes:
    - name: pod-tmp
      emptyDir: {}
    - name: horizon-bin
      configMap:
        name: horizon-bin
        defaultMode: 0555

