---
# Source: keystone/templates/job-credential-setup.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: keystone-credential-setup
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: keystone-credential-setup
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
      - create
      - update
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: keystone-credential-setup
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: keystone-credential-setup
subjects:
  - kind: ServiceAccount
    name: keystone-credential-setup
    namespace: openstack
---
apiVersion: batch/v1
kind: Job
metadata:
  name: keystone-credential-setup
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
spec:
  template:
    metadata:
      labels:
        release_group: release-name
        application: keystone
        component: credential-setup
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "3c7e86e0f2cf5ada7f6d146e293aed60ef8b21fb8571a2dd377de73f53abce8b"
        configmap-etc-hash: "bf6efc0f7952f575e06ff0260408b5425ef8c1ad32219940a7f26fe1da0d6348"
        
    spec:
      serviceAccountName: keystone-credential-setup
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: ""
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            null
            
      restartPolicy: OnFailure
      nodeSelector:
        openstack-control-plane: enabled
      containers:
        - name: keystone-credential-setup
          image: "docker.io/openstackhelm/keystone:stein-ubuntu_bionic"
          imagePullPolicy: IfNotPresent
          
          env:
            - name: KEYSTONE_USER
              value: "keystone"
            - name: KEYSTONE_GROUP
              value: "keystone"
            - name: KUBERNETES_NAMESPACE
              value: "openstack"
            - name: KEYSTONE_KEYS_REPOSITORY
              value: "/etc/keystone/credential-keys/"
          command:
            - python
            - /tmp/fernet-manage.py
            - credential_setup
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: etckeystone
              mountPath: /etc/keystone
            - name: credential-keys
              mountPath: "/etc/keystone/credential-keys/"
            - name: keystone-etc
              mountPath: /etc/keystone/keystone.conf
              subPath: keystone.conf
              readOnly: true
            - name: keystone-etc
              mountPath: /etc/keystone/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: keystone-bin
              mountPath: /tmp/fernet-manage.py
              subPath: fernet-manage.py
              readOnly: true

      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: etckeystone
          emptyDir: {}
        - name: credential-keys
          emptyDir: {}
        - name: keystone-etc
          secret:
            secretName: keystone-etc
            defaultMode: 0444
        - name: keystone-bin
          configMap:
            name: keystone-bin
            defaultMode: 0555

