---
# Source: glance/templates/pdb-api.yaml

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: glance-api
spec:
  minAvailable: 0
  selector:
    matchLabels:
      release_group: release-name
      application: glance
      component: api
