---
# Source: cinder/templates/job-backup-storage-init.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cinder-backup-storage-init
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cinder-backup-storage-init
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cinder-backup-storage-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cinder-backup-storage-init
subjects:
  - kind: ServiceAccount
    name: cinder-backup-storage-init
    namespace: openstack
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cinder-backup-storage-init
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
spec:
  template:
    metadata:
      labels:
        release_group: release-name
        application: cinder
        component: storage-init
      annotations:
        
    spec:
      serviceAccountName: cinder-backup-storage-init
      securityContext:
      restartPolicy: OnFailure
      nodeSelector:
        openstack-control-plane: enabled
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: ""
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
      containers:
        - name: cinder-backup-storage-init
          image: "docker.io/openstackhelm/ceph-config-helper:ubuntu_bionic-20191216"
          imagePullPolicy: IfNotPresent
          
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STORAGE_BACKEND
              value: "cinder.backup.drivers.swift"
          command:
            - /tmp/backup-storage-init.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: cinder-bin
              mountPath: /tmp/backup-storage-init.sh
              subPath: backup-storage-init.sh
              readOnly: true
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: cinder-bin
          configMap:
            name: cinder-bin
            defaultMode: 0555
