---
# Source: cinder/templates/job-db-init.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cinder-db-init
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-cinder-db-init
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-openstack-cinder-db-init
subjects:
  - kind: ServiceAccount
    name: cinder-db-init
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-openstack-cinder-db-init
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "cinder-db-init"
spec:
  backoffLimit: 1000
  template:
    metadata:
      labels:
        release_group: release-name
        application: cinder
        component: db-init
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
    spec:
      serviceAccountName: cinder-db-init
      restartPolicy: OnFailure
      nodeSelector:
        openstack-control-plane: enabled
        
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:mariadb"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
      containers:

        - name: "cinder-db-init-0"
          image: docker.io/openstackhelm/heat:stein-ubuntu_bionic
          imagePullPolicy: IfNotPresent
          
          env:
            - name: ROOT_DB_CONNECTION
              valueFrom:
                secretKeyRef:
                  name: "cinder-db-admin"
                  key: DB_CONNECTION
            - name: OPENSTACK_CONFIG_FILE
              value: "/etc/cinder/cinder.conf"
            - name: OPENSTACK_CONFIG_DB_SECTION
              value: "database"
            - name: OPENSTACK_CONFIG_DB_KEY
              value: "connection"
          command:
            - /tmp/db-init.py
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: db-init-sh
              mountPath: /tmp/db-init.py
              subPath: db-init.py
              readOnly: true
            - name: etc-service
              mountPath: "/etc/cinder"
            - name: db-init-conf
              mountPath: "/etc/cinder/cinder.conf"
              subPath: "cinder.conf"
              readOnly: true
            - name: db-init-conf
              mountPath: "/etc/cinder/logging.conf"
              subPath: "logging.conf"
              readOnly: true
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: db-init-sh
          configMap:
            name: "cinder-bin"
            defaultMode: 0555
        - name: etc-service
          emptyDir: {}
        - name: db-init-conf
          secret:
            secretName: "cinder-etc"
            defaultMode: 0444
