---
# Source: cinder/templates/job-storage-init.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: cinder-storage-init
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: Role
metadata:
  name: cinder-storage-init
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - create
      - update
      - patch
---
apiVersion: rbac.authorization.k8s.io/v1beta1
kind: RoleBinding
metadata:
  name: cinder-storage-init
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: cinder-storage-init
subjects:
  - kind: ServiceAccount
    name: cinder-storage-init
    namespace: openstack
---
apiVersion: batch/v1
kind: Job
metadata:
  name: cinder-storage-init
spec:
  template:
    metadata:
      labels:
        release_group: release-name
        application: cinder
        component: storage-init
    spec:
      serviceAccountName: cinder-storage-init
      securityContext:
      restartPolicy: OnFailure
      nodeSelector:
        openstack-control-plane: enabled
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: ""
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
        - name: ceph-keyring-placement
          image: "docker.io/openstackhelm/ceph-config-helper:ubuntu_bionic-20191216"
          imagePullPolicy: IfNotPresent
          securityContext:
            runAsUser: 0
          command:
            - /tmp/ceph-admin-keyring.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: etcceph
              mountPath: /etc/ceph
            - name: cinder-bin
              mountPath: /tmp/ceph-admin-keyring.sh
              subPath: ceph-admin-keyring.sh
              readOnly: true
            - name: ceph-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
            
        
      containers:
        - name: cinder-storage-init-rbd1
          image: "docker.io/openstackhelm/ceph-config-helper:ubuntu_bionic-20191216"
          imagePullPolicy: IfNotPresent
          
          env:
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  fieldPath: metadata.namespace
            - name: STORAGE_BACKEND
              value: "cinder.volume.drivers.rbd.RBDDriver"
            - name: RBD_POOL_NAME
              value: "cinder.volumes"
            - name: RBD_POOL_APP_NAME
              value: "cinder-volume"
            - name: RBD_POOL_USER
              value: "cinder"
            - name: RBD_POOL_CRUSH_RULE
              value: "replicated_rule"
            - name: RBD_POOL_REPLICATION
              value: "3"
            - name: RBD_POOL_CHUNK_SIZE
              value: "8"
            - name: RBD_POOL_SECRET
              value: "cinder-volume-rbd-keyring"
          command:
            - /tmp/storage-init.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: cinder-bin
              mountPath: /tmp/storage-init.sh
              subPath: storage-init.sh
              readOnly: true
            - name: etcceph
              mountPath: /etc/ceph
            - name: ceph-etc
              mountPath: /etc/ceph/ceph.conf
              subPath: ceph.conf
              readOnly: true
            - name: ceph-keyring
              mountPath: /tmp/client-keyring
              subPath: key
              readOnly: true
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: cinder-bin
          configMap:
            name: cinder-bin
            defaultMode: 0555
        - name: etcceph
          emptyDir: {}
        - name: ceph-etc
          configMap:
            name: ceph-etc
            defaultMode: 0444
        - name: ceph-keyring
          secret:
            secretName: pvc-ceph-client-key
