---
# Source: ingress/templates/configmap-conf.yaml
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ingress-conf
data:
  enable-underscores-in-headers: "true"
  enable-vts-status: "true"
  server-tokens: "false"
  
