---
# Source: ceph-provisioners/templates/deployment-rbd-provisioner.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-ceph-rbd-provisioner
  namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-release-name-ceph-rbd-provisioner
  namespace: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-ceph-release-name-ceph-rbd-provisioner
subjects:
  - kind: ServiceAccount
    name: release-name-ceph-rbd-provisioner
    namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-ceph-release-name-ceph-rbd-provisioner
  namespace: ceph
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: release-name-ceph-rbd-provisioner
rules:
  - apiGroups:
      - ''
    resources:
      - persistentvolumes
    verbs:
      - get
      - list
      - watch
      - create
      - delete
  - apiGroups:
      - ''
    resources:
      - persistentvolumeclaims
    verbs:
      - get
      - list
      - watch
      - update
  - apiGroups:
      - storage.k8s.io
    resources:
      - storageclasses
    verbs:
      - get
      - list
      - watch
  - apiGroups:
      - ''
    resources:
      - events
    verbs:
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - ''
    resources:
      - services
      - endpoints
    verbs:
      - get
      - list
      - watch
      - create
      - update
      - patch
  - apiGroups:
      - extensions
    resources:
      - podsecuritypolicies
    resourceNames:
      - rbd-provisioner
    verbs:
      - use
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: release-name-ceph-rbd-provisioner-run-rbd-provisioner
subjects:
  - kind: ServiceAccount
    name: release-name-ceph-rbd-provisioner
    namespace: ceph
roleRef:
  kind: ClusterRole
  name: release-name-ceph-rbd-provisioner
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-ceph-rbd-provisioner
rules:
  - apiGroups:
      - ""
    resources:
      - secrets
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-ceph-rbd-provisioner
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-ceph-rbd-provisioner
subjects:
  - kind: ServiceAccount
    name: release-name-ceph-rbd-provisioner
    namespace: ceph
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ceph-rbd-provisioner
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
  labels:
    release_group: release-name
    application: rbd
    component: provisioner
spec:
  replicas: 2
  selector:
    matchLabels:
      release_group: release-name
      application: rbd
      component: provisioner
  revisionHistoryLimit: 
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        release_group: release-name
        application: rbd
        component: provisioner
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        
        container.apparmor.security.beta.kubernetes.io/ceph-rbd-provisioner: runtime/default
        container.apparmor.security.beta.kubernetes.io/init: runtime/default
    spec:
      securityContext:
        runAsUser: 0
        
      serviceAccountName: release-name-ceph-rbd-provisioner
      affinity:
        
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: release_group
                    operator: In
                    values:
                    - release-name
                  - key: application
                    operator: In
                    values:
                    - rbd
                  - key: component
                    operator: In
                    values:
                    - provisioner
                  
              topologyKey: kubernetes.io/hostname
            weight: 10
      nodeSelector:
        openstack-control-plane: enabled
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "ceph:ceph-mon"
            - name: DEPENDENCY_JOBS
              value: "ceph-rbd-pool"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
      containers:
        - name: ceph-rbd-provisioner
          image: "docker.io/openstackhelm/ceph-rbd-provisioner:ubuntu_bionic-20200416"
          imagePullPolicy: IfNotPresent
          
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            
          env:
            - name: PROVISIONER_NAME
              value: ceph.com/rbd
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
          command:
            - /tmp/provisioner-rbd-start.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: ceph-provisioners-bin
              mountPath: /tmp/provisioner-rbd-start.sh
              subPath: provisioner-rbd-start.sh
              readOnly: true
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: pod-run
          emptyDir:
            medium: "Memory"
        - name: pod-etc-ceph
          emptyDir: {}
        - name: ceph-provisioners-bin
          configMap:
            name: "release-name-ceph-prov-bin"
            defaultMode: 0555
