---
# Source: ceph-provisioners/templates/storageclass.yaml

---
---
apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  annotations:
    storageclass.kubernetes.io/is-default-class: "true"
  name: general
provisioner: ceph.com/rbd
parameters:
  monitors: ceph-mon.ceph.svc.cluster.local:6789
  adminId: "admin"
  adminSecretName: "pvc-ceph-conf-combined-storageclass"
  adminSecretNamespace: "ceph"
  imageFeatures: "layering"
  imageFormat: "2"
  pool: "rbd"
  userId: "admin"
  userSecretName: "pvc-ceph-client-key"
allowVolumeExpansion: true
