---
# Source: ceph-client/templates/deployment-mgr.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-mgr
  namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-ceph-mgr
  namespace: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-ceph-ceph-mgr
subjects:
  - kind: ServiceAccount
    name: ceph-mgr
    namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-ceph-ceph-mgr
  namespace: ceph
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
kind: Deployment
apiVersion: apps/v1
metadata:
  name: ceph-mgr
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
  labels:
    release_group: release-name
    application: ceph
    component: mgr
spec:
  replicas: 2
  selector:
    matchLabels:
      release_group: release-name
      application: ceph
      component: mgr
  strategy:
    type: Recreate
  template:
    metadata:
      labels:
        release_group: release-name
        application: ceph
        component: mgr
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "5fd1036f20f2a0cf409d2c0ea9cf55b5a1802d26108b1fb59968086d8ade73b0"
        configmap-etc-client-hash: "3b5543419226621c48cd92113f206d5d80457f15bc0e0e413118f8c76edd00b5"
        
        container.apparmor.security.beta.kubernetes.io/ceph-mgr: runtime/default
        container.apparmor.security.beta.kubernetes.io/ceph-init-dirs: runtime/default
    spec:
      securityContext:
        runAsUser: 65534
        
      serviceAccountName: ceph-mgr
      affinity:
        
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: release_group
                    operator: In
                    values:
                    - release-name
                  - key: application
                    operator: In
                    values:
                    - ceph
                  - key: component
                    operator: In
                    values:
                    - mgr
                  
              topologyKey: kubernetes.io/hostname
            weight: 10
      nodeSelector:
        ceph-mgr: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "ceph:ceph-mon"
            - name: DEPENDENCY_JOBS
              value: "ceph-storage-keys-generator,ceph-mgr-keyring-generator"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
        - name: ceph-init-dirs
          image: "docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416"
          imagePullPolicy: IfNotPresent
          
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            
          command:
            - /tmp/init-dirs.sh
          env:
            - name: CLUSTER
              value: "ceph"
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: ceph-client-bin
              mountPath: /tmp/init-dirs.sh
              subPath: init-dirs.sh
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
      containers:
        - name: ceph-mgr
          image: "docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416"
          imagePullPolicy: IfNotPresent
          
          
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            
          env:
            - name: CLUSTER
              value: "ceph"
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: MON_PORT
              value: "6789"
            - name: MON_PORT_V2
              value: "3300"
            - name: ENABLED_MODULES
              value: |-
                restful
                status
                prometheus
                balancer
                iostat
                pg_autoscaler
          command:
            - /mgr-start.sh
          ports:
            - name: mgr
              containerPort: 7000
            - name: metrics
              containerPort: 9283
          livenessProbe:
           exec:
            command:
             - /tmp/mgr-check.sh
             - liveness
           initialDelaySeconds: 30
           timeoutSeconds: 5
          readinessProbe:
           exec:
            command:
             - /tmp/mgr-check.sh
             - readiness
           initialDelaySeconds: 30
           timeoutSeconds: 5
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: ceph-client-bin
              mountPath: /mgr-start.sh
              subPath: mgr-start.sh
              readOnly: true
            - name: ceph-client-bin
              mountPath: /tmp/mgr-check.sh
              subPath: mgr-check.sh
              readOnly: true
            - name: ceph-client-bin
              mountPath: /tmp/utils-checkDNS.sh
              subPath: utils-checkDNS.sh
              readOnly: true
            - name: ceph-client-etc
              mountPath: /etc/ceph/ceph.conf.template
              subPath: ceph.conf
              readOnly: true
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
              readOnly: true
            - name: ceph-bootstrap-mgr-keyring
              mountPath: /var/lib/ceph/bootstrap-mgr/ceph.keyring
              subPath: ceph.keyring
              readOnly: false
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: ceph-client-bin
              mountPath: /tmp/utils-checkPGs.py
              subPath: utils-checkPGs.py
              readOnly: true
            - name: ceph-client-bin
              mountPath: /tmp/utils-checkPGs.sh
              subPath: utils-checkPGs.sh
              readOnly: true
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: pod-run
          emptyDir:
            medium: "Memory"
        - name: pod-etc-ceph
          emptyDir: {}
        - name: ceph-client-bin
          configMap:
            name: ceph-client-bin
            defaultMode: 0555
        - name: ceph-client-etc
          configMap:
            name: ceph-client-etc
            defaultMode: 0444
        - name: pod-var-lib-ceph
          emptyDir: {}
        - name: ceph-client-admin-keyring
          secret:
            secretName: ceph-client-admin-keyring
        - name: ceph-bootstrap-mgr-keyring
          secret:
            secretName: ceph-bootstrap-mgr-keyring
