---
# Source: ceph-client/templates/pod-helm-tests.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-test
  namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-release-name-test
  namespace: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-ceph-release-name-test
subjects:
  - kind: ServiceAccount
    name: release-name-test
    namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-ceph-release-name-test
  namespace: ceph
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
apiVersion: v1
kind: Pod
metadata:
  name: release-name-test
  labels:
    release_group: release-name
    application: ceph-client
    component: test
  annotations:
    "helm.sh/hook": test-success
spec:
  securityContext:
    runAsUser: 65534
    
  restartPolicy: Never
  serviceAccountName: release-name-test
  nodeSelector:
    openstack-control-plane: enabled
  initContainers:
    
    - name: init
      image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
      imagePullPolicy: IfNotPresent  
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsUser: 65534
        
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INTERFACE_NAME
          value: eth0
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
        - name: DEPENDENCY_SERVICE
          value: "ceph:ceph-mon,ceph:ceph-mgr"
        - name: DEPENDENCY_JOBS
          value: "ceph-rbd-pool,ceph-mgr-keyring-generator"
        - name: DEPENDENCY_DAEMONSET
          value: ""
        - name: DEPENDENCY_CONTAINER
          value: ""
        - name: DEPENDENCY_POD_JSON
          value: ""
        - name: DEPENDENCY_CUSTOM_RESOURCE
          value: ""
      command:
        - kubernetes-entrypoint
      volumeMounts:
        []
        
  containers:
    - name: ceph-cluster-helm-test
      image: "docker.io/openstackhelm/ceph-config-helper:ubuntu_bionic-20200416"
      imagePullPolicy: IfNotPresent
      
      
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        
      env:
        - name: CEPH_DEPLOYMENT_NAMESPACE
          value: ceph
        - name: EXPECTED_OSDS
          value: "8"
        - name: REQUIRED_PERCENT_OF_OSDS
          value: "75"
        - name: EXPECTED_CRUSHRULE
          value: "replicated_rule"
        - name: MGR_COUNT
          value: "2"
        - name: ENABLE_AUTOSCALER
          value: "true"
        - name: RBD
          value: "3"
        - name: CEPHFS_METADATA
          value: "3"
        - name: CEPHFS_DATA
          value: "3"
        - name: _RGW_ROOT
          value: "3"
        - name: DEFAULT_RGW_CONTROL
          value: "3"
        - name: DEFAULT_RGW_DATA_ROOT
          value: "3"
        - name: DEFAULT_RGW_GC
          value: "3"
        - name: DEFAULT_RGW_LOG
          value: "3"
        - name: DEFAULT_RGW_INTENT-LOG
          value: "3"
        - name: DEFAULT_RGW_META
          value: "3"
        - name: DEFAULT_RGW_USAGE
          value: "3"
        - name: DEFAULT_RGW_USERS_KEYS
          value: "3"
        - name: DEFAULT_RGW_USERS_EMAIL
          value: "3"
        - name: DEFAULT_RGW_USERS_SWIFT
          value: "3"
        - name: DEFAULT_RGW_USERS_UID
          value: "3"
        - name: DEFAULT_RGW_BUCKETS_EXTRA
          value: "3"
        - name: DEFAULT_RGW_BUCKETS_INDEX
          value: "3"
        - name: DEFAULT_RGW_BUCKETS_DATA
          value: "3"
      command:
        - /tmp/helm-tests.sh
      volumeMounts:
        - name: pod-tmp
          mountPath: /tmp
        - name: ceph-client-bin
          mountPath: /tmp/helm-tests.sh
          subPath: helm-tests.sh
          readOnly: true
        - name: ceph-client-admin-keyring
          mountPath: /etc/ceph/ceph.client.admin.keyring
          subPath: ceph.client.admin.keyring
          readOnly: true
        - name: ceph-client-etc
          mountPath: /etc/ceph/ceph.conf
          subPath: ceph.conf
          readOnly: true
  volumes:
    - name: pod-tmp
      emptyDir: {}
    - name: ceph-client-bin
      configMap:
        name: ceph-client-bin
        defaultMode: 0555
    - name: ceph-client-admin-keyring
      secret:
        secretName: ceph-client-admin-keyring
    - name: ceph-client-etc
      configMap:
        name: ceph-client-etc
        defaultMode: 0444
