---
# Source: ceph-client/templates/service-mgr.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: ceph-mgr
  labels:
    release_group: release-name
    application: ceph
    component: manager
  annotations:
    
    prometheus.io/scrape: "true"
    prometheus.io/port: "9283"
spec:
  ports:
  - name: ceph-mgr
    port: 7000
    protocol: TCP
    targetPort: 7000
  
  - name: metrics
    protocol: TCP
    port: 9283
  
  selector:
    release_group: release-name
    application: ceph
    component: mgr
