---
# Source: rabbitmq/templates/job-cluster-wait.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-cluster-wait
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-release-name-cluster-wait
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-openstack-release-name-cluster-wait
subjects:
  - kind: ServiceAccount
    name: release-name-cluster-wait
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-openstack-release-name-cluster-wait
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
---
apiVersion: batch/v1
kind: Job
metadata:
  name: "release-name-cluster-wait"
  labels:
    release_group: release-name
    application: rabbitmq
    component: cluster-wait
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
spec:
  template:
    metadata:
      labels:
        release_group: release-name
        application: rabbitmq
        component: cluster-wait
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "0d07c5311e14b81dd7fd33a45c19fb10e839b05b47d9527cbf7b8bffce05cea0"
        configmap-etc-hash: "2f325879f2f3dc45297630f246c3e1cc362a602e991221a7582365bdd82b27f7"
        
    spec:
      securityContext:
        runAsUser: 999
        
      serviceAccountName: release-name-cluster-wait
      restartPolicy: OnFailure
      nodeSelector:
        openstack-control-plane: "enabled"
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:rabbitmq"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
        - name: rabbitmq-cookie
          image: "docker.io/rabbitmq:3.7.13-management"
          imagePullPolicy: IfNotPresent
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            
          command:
            - /tmp/rabbitmq-cookie.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: rabbitmq-bin
              mountPath: /tmp/rabbitmq-cookie.sh
              subPath: rabbitmq-cookie.sh
              readOnly: true
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
            - name: rabbitmq-erlang-cookie
              mountPath: /var/run/lib/rabbitmq/.erlang.cookie
              subPath: erlang_cookie
              readOnly: true
      containers:
        - name: release-name-rabbitmq-cluster-wait
          image: "docker.io/rabbitmq:3.7.13-management"
          imagePullPolicy: IfNotPresent
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            
          env:
            - name: RABBITMQ_ADMIN_CONNECTION
              value: "rabbit://rabbitmq:password@rabbitmq.openstack.svc.cluster.local:15672/"
            - name: RABBIT_REPLICA_COUNT
              value: "2"
          command:
            - /tmp/rabbitmq-wait-for-cluster.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: rabbitmq-bin
              mountPath: /tmp/rabbitmq-wait-for-cluster.sh
              subPath: rabbitmq-wait-for-cluster.sh
              readOnly: true
            - name: rabbitmq-data
              mountPath: /var/lib/rabbitmq
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: rabbitmq-data
          emptyDir: {}
        - name: rabbitmq-bin
          configMap:
            name: "release-name-rabbitmq-bin"
            defaultMode: 0555
        - name: rabbitmq-erlang-cookie
          secret:
            secretName: "release-name-erlang-cookie"
            defaultMode: 0444
