---
# Source: rabbitmq/templates/pod-test.yaml








---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: release-name-test
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-release-name-test
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-openstack-release-name-test
subjects:
  - kind: ServiceAccount
    name: release-name-test
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-openstack-release-name-test
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
apiVersion: v1
kind: Pod
metadata:
  name: "release-name-test"
  labels:
    release_group: release-name
    application: rabbitmq
    component: test
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
    "helm.sh/hook": test-success
spec:
  securityContext:
    runAsUser: 999
    
  serviceAccountName: release-name-test
  nodeSelector:
    openstack-control-plane: "enabled"
  restartPolicy: Never
  initContainers:
    
    - name: init
      image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
      imagePullPolicy: IfNotPresent  
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        runAsUser: 65534
        
      env:
        - name: POD_NAME
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.name
        - name: NAMESPACE
          valueFrom:
            fieldRef:
              apiVersion: v1
              fieldPath: metadata.namespace
        - name: INTERFACE_NAME
          value: eth0
        - name: PATH
          value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
        - name: DEPENDENCY_SERVICE
          value: "openstack:rabbitmq"
        - name: DEPENDENCY_JOBS
          value: "release-name-cluster-wait"
        - name: DEPENDENCY_DAEMONSET
          value: ""
        - name: DEPENDENCY_CONTAINER
          value: ""
        - name: DEPENDENCY_POD_JSON
          value: ""
        - name: DEPENDENCY_CUSTOM_RESOURCE
          value: ""
      command:
        - kubernetes-entrypoint
      volumeMounts:
        []
        
  containers:
    - name: release-name-rabbitmq-test
      image: "docker.io/rabbitmq:3.7.13-management"
      imagePullPolicy: IfNotPresent
      
      securityContext:
        allowPrivilegeEscalation: false
        readOnlyRootFilesystem: true
        
      env:
        - name: RABBITMQ_ADMIN_CONNECTION
          value: "rabbit://rabbitmq:password@rabbitmq.openstack.svc.cluster.local:15672/"
        - name: RABBIT_REPLICA_COUNT
          value: "2"
      command:
        - /tmp/rabbitmq-test.sh
      volumeMounts:
        - name: pod-tmp
          mountPath: /tmp
        - name: rabbitmq-bin
          mountPath: /tmp/rabbitmq-test.sh
          subPath: rabbitmq-test.sh
          readOnly: true
  volumes:
    - name: pod-tmp
      emptyDir: {}
    - name: rabbitmq-bin
      configMap:
        name: "release-name-rabbitmq-bin"
        defaultMode: 0555
