---
# Source: ceph-mon/templates/daemonset-mon.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: ceph-mon
  namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-ceph-mon
  namespace: ceph
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-ceph-ceph-mon
subjects:
  - kind: ServiceAccount
    name: ceph-mon
    namespace: ceph
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-ceph-ceph-mon
  namespace: ceph
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - jobs
      - pods
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ceph-mon
rules:
  - apiGroups:
      - ""
    resources:
      - pods
      - endpoints
    verbs:
      - get
      - list
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ceph-mon
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ceph-mon
subjects:
  - kind: ServiceAccount
    name: ceph-mon
    namespace: ceph
---
kind: DaemonSet
apiVersion: apps/v1
metadata:
  name: ceph-mon
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
  labels:
    release_group: release-name
    application: ceph
    component: mon
spec:
  selector:
    matchLabels:
      release_group: release-name
      application: ceph
      component: mon
  
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        release_group: release-name
        application: ceph
        component: mon
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-etc-hash: "d40a22b44a60f201e541d4ac90debedd4cb1c943a4090a4fc332f19eb96f4f5a"
        configmap-bin-hash: "08969de325d0d29e2f9feea3f329f524d0090c053b8b6f413fbd99732c068d8d"
        
        container.apparmor.security.beta.kubernetes.io/ceph-mon: runtime/default
        container.apparmor.security.beta.kubernetes.io/ceph-init-dirs: runtime/default
        container.apparmor.security.beta.kubernetes.io/ceph-log-ownership: runtime/default
    spec:
      securityContext:
        runAsUser: 65534
        
      serviceAccountName: ceph-mon
      nodeSelector:
        ceph-mon: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: ""
            - name: DEPENDENCY_JOBS
              value: "ceph-storage-keys-generator,ceph-mon-keyring-generator"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
        - name: ceph-init-dirs
          image: "docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416"
          imagePullPolicy: IfNotPresent
          
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            
          command:
            - /tmp/init-dirs.sh
          env:
            - name: CLUSTER
              value: "ceph"
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: ceph-mon-bin
              mountPath: /tmp/init-dirs.sh
              subPath: init-dirs.sh
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
        - name: ceph-log-ownership
          image: "docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416"
          imagePullPolicy: IfNotPresent
          
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            
          command:
            - chown
            - -R
            - ceph:root
            - /var/log/ceph
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: pod-var-log
              mountPath: /var/log/ceph
              readOnly: false
      containers:
        - name: ceph-mon
          image: "docker.io/openstackhelm/ceph-daemon:ubuntu_bionic-20200416"
          imagePullPolicy: IfNotPresent
          
          
          securityContext:
            readOnlyRootFilesystem: true
            runAsUser: 0
            
          env:
            - name: CLUSTER
              value: "ceph"
            - name: K8S_HOST_NETWORK
              value: "1"
            - name: MONMAP
              value: /var/lib/ceph/mon/monmap
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: CEPH_PUBLIC_NETWORK
              value: "20.0.0.0/24"
            - name: KUBECTL_PARAM
              value:           -l application=ceph -l component=mon
            - name: MON_PORT
              value: "6789"
            - name: MON_PORT_V2
              value: "3300"
            - name: MON_IP
              valueFrom:
                fieldRef:
                  fieldPath: status.podIP
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          command:
            - /tmp/mon-start.sh
          lifecycle:
            preStop:
                exec:
                  command:
                    - /tmp/mon-stop.sh
          ports:
            - containerPort: 6789
            - containerPort: 3300
          livenessProbe:
           exec:
            command:
             - /tmp/mon-check.sh
             - liveness
           initialDelaySeconds: 360
           periodSeconds: 180
          readinessProbe:
           exec:
            command:
             - /tmp/mon-check.sh
             - readiness
           initialDelaySeconds: 60
           periodSeconds: 60
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: pod-run
              mountPath: /run
            - name: pod-etc-ceph
              mountPath: /etc/ceph
            - name: ceph-mon-bin
              mountPath: /tmp/mon-start.sh
              subPath: mon-start.sh
              readOnly: true
            - name: ceph-mon-bin
              mountPath: /tmp/mon-stop.sh
              subPath: mon-stop.sh
              readOnly: true
            - name: ceph-mon-bin
              mountPath: /tmp/mon-check.sh
              subPath: mon-check.sh
              readOnly: true
            - name: ceph-mon-bin
              mountPath: /tmp/checkObjectReplication.py
              subPath: utils-checkObjectReplication.py
              readOnly: true
            - name: ceph-mon-bin
              mountPath: /tmp/utils-checkDNS.sh
              subPath: utils-checkDNS.sh
              readOnly: true
            - name: ceph-mon-etc
              mountPath: /etc/ceph/ceph.conf.template
              subPath: ceph.conf
              readOnly: true
            - name: ceph-client-admin-keyring
              mountPath: /etc/ceph/ceph.client.admin.keyring
              subPath: ceph.client.admin.keyring
              readOnly: true
            - name: ceph-mon-keyring
              mountPath: /etc/ceph/ceph.mon.keyring.seed
              subPath: ceph.mon.keyring
              readOnly: true
            - name: ceph-bootstrap-osd-keyring
              mountPath: /var/lib/ceph/bootstrap-osd/ceph.keyring
              subPath: ceph.keyring
              readOnly: true
            - name: ceph-bootstrap-mds-keyring
              mountPath: /var/lib/ceph/bootstrap-mds/ceph.keyring
              subPath: ceph.keyring
              readOnly: true
            - name: pod-var-lib-ceph
              mountPath: /var/lib/ceph
              readOnly: false
            - name: pod-var-log
              mountPath: /var/log/ceph
              readOnly: false
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: pod-run
          emptyDir:
            medium: "Memory"
        - name: pod-etc-ceph
          emptyDir: {}
        - name: pod-var-log
          emptyDir: {}
        - name: ceph-mon-bin
          configMap:
            name: ceph-mon-bin
            defaultMode: 0555
        - name: ceph-mon-etc
          configMap:
            name: ceph-mon-etc
            defaultMode: 0444
        - name: pod-var-lib-ceph
          hostPath:
            path: /var/lib/openstack-helm/ceph/mon
        - name: ceph-client-admin-keyring
          secret:
            secretName: ceph-client-admin-keyring
        - name: ceph-mon-keyring
          secret:
            secretName: ceph-mon-keyring
        - name: ceph-bootstrap-osd-keyring
          secret:
            secretName: ceph-bootstrap-osd-keyring
        - name: ceph-bootstrap-mds-keyring
          secret:
            secretName: ceph-bootstrap-mds-keyring
