---
# Source: ceph-mon/templates/service-mon-discovery.yaml

---
kind: Service
apiVersion: v1
metadata:
  name: ceph-mon-discovery
  annotations:
    # In kubernetes 1.6 and beyond, it seems there was a change in behavior
    # requiring us to tolerate unready endpoints to form a quorum.  I can only
    # guess at some small timing change causing statefulset+2 to not see the
    # now ready statefulset+1, and because we do not tolerate unready endpoints
    # a newly provisioned ceph-mon will most certainly never see itself in the
    # peer list.  This change allows us to form a quorum reliably everytime
    service.alpha.kubernetes.io/tolerate-unready-endpoints: "true"
spec:
  ports:
  - name: mon
    port: 6789
    protocol: TCP
    targetPort: 6789
  - name: mon-msgr2
    port: 3300
    protocol: TCP
    targetPort: 3300
  selector:
    release_group: release-name
    application: ceph
    component: mon
  clusterIP: None
