---
# Source: openvswitch/templates/daemonset-ovs-vswitchd.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: openvswitch-vswitchd
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-openvswitch-vswitchd
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-openstack-openvswitch-vswitchd
subjects:
  - kind: ServiceAccount
    name: openvswitch-vswitchd
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-openstack-openvswitch-vswitchd
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - pods
---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: openvswitch-vswitchd
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
  labels:
    release_group: release-name
    application: openvswitch
    component: openvswitch-vswitchd
spec:
  selector:
    matchLabels:
      release_group: release-name
      application: openvswitch
      component: openvswitch-vswitchd
  
  minReadySeconds: 0
  updateStrategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
  template:
    metadata:
      labels:
        release_group: release-name
        application: openvswitch
        component: openvswitch-vswitchd
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "97b738fcd4a6fba1688a00d3578e49eb658d2fe33b8b2a6512a3dfeae35f2c8d"
        
    spec:
      shareProcessNamespace: true
      serviceAccountName: openvswitch-vswitchd
      securityContext:
        runAsUser: 0
        
      nodeSelector:
        openvswitch: enabled
      dnsPolicy: ClusterFirstWithHostNet
      hostNetwork: true
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: ""
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: "[{\"labels\":{\"application\":\"openvswitch\",\"component\":\"openvswitch-vswitchd-db\"},\"requireSameNode\":true}]"
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            []
            
        - name: openvswitch-vswitchd-modules
          image: "docker.io/openstackhelm/openvswitch:ubuntu_bionic-20191031"
          imagePullPolicy: IfNotPresent
          
          securityContext:
            capabilities:
              add:
              - SYS_MODULE
            readOnlyRootFilesystem: true
            runAsUser: 0
            
          command:
            - /tmp/openvswitch-vswitchd-init-modules.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: openvswitch-bin
              mountPath: /tmp/openvswitch-vswitchd-init-modules.sh
              subPath: openvswitch-vswitchd-init-modules.sh
              readOnly: true
            - name: host-rootfs
              mountPath: /mnt/host-rootfs
              readOnly: true
      containers:
        - name: openvswitch-vswitchd
          image: "docker.io/openstackhelm/openvswitch:ubuntu_bionic-20191031"
          imagePullPolicy: IfNotPresent
          
          securityContext:
            capabilities:
              add:
              - NET_ADMIN
            readOnlyRootFilesystem: true
            runAsUser: 0
            
          
          # ensures this container can speak to the ovs database
          # successfully before its marked as ready
          livenessProbe:
            exec:
              command:
              - /usr/bin/ovs-appctl
              - bond/list
            initialDelaySeconds: 60
            periodSeconds: 30
            timeoutSeconds: 5
          
          readinessProbe:
            exec:
              command:
              - /bin/bash
              - -c
              - /usr/bin/ovs-vsctl show
            failureThreshold: 3
            periodSeconds: 10
            timeoutSeconds: 1
          
          command:
            - /tmp/openvswitch-vswitchd.sh
            - start
          lifecycle:
            postStart:
              exec:
                command:
                  - /tmp/openvswitch-vswitchd.sh
                  - poststart
            preStop:
              exec:
                command:
                  - /tmp/openvswitch-vswitchd.sh
                  - stop
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: openvswitch-bin
              mountPath: /tmp/openvswitch-vswitchd.sh
              subPath: openvswitch-vswitchd.sh
              readOnly: true
            - name: run
              mountPath: /run
      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: openvswitch-bin
          configMap:
            name: openvswitch-bin
            defaultMode: 0555
        - name: run
          hostPath:
            path: /run
            type: Directory
        - name: host-rootfs
          hostPath:
            path: /
            type: Directory
