---
# Source: nova/templates/deployment-placement.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nova-placement-api
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-nova-placement-api
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-openstack-nova-placement-api
subjects:
  - kind: ServiceAccount
    name: nova-placement-api
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-openstack-nova-placement-api
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-placement-api
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
  labels:
    release_group: release-name
    application: nova
    component: placement
spec:
  replicas: 2
  selector:
    matchLabels:
      release_group: release-name
      application: nova
      component: placement
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        release_group: release-name
        application: nova
        component: placement
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "86616d85a7e726a16bc68931e0e2773ba86ae9be6058ec92db7d613dd4f2f1eb"
        configmap-etc-hash: "f99cc432cbe36c74dc6c48c6ec3be9040bec41a4baf5f24d1ccbb200d3ecf09c"
        
    spec:
      serviceAccountName: nova-placement-api
      affinity:
        
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: release_group
                    operator: In
                    values:
                    - release-name
                  - key: application
                    operator: In
                    values:
                    - nova
                  - key: component
                    operator: In
                    values:
                    - placement
                  
              topologyKey: kubernetes.io/hostname
            weight: 10
      nodeSelector:
        openstack-control-plane: enabled
      terminationGracePeriodSeconds: 30
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:rabbitmq,openstack:mariadb,openstack:keystone-api"
            - name: DEPENDENCY_JOBS
              value: "nova-db-sync,nova-ks-user,nova-ks-endpoints,nova-rabbit-init"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            null
            
      containers:
        - name: nova-placement-api
          image: "docker.io/openstackhelm/nova:stein-ubuntu_bionic"
          imagePullPolicy: IfNotPresent
          
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            
          command:
            - /tmp/nova-placement-api.sh
            - start
          lifecycle:
            preStop:
              exec:
                command:
                  - /tmp/nova-placement-api.sh
                  - stop
          ports:
            - name: p-api
              containerPort: 8778
          readinessProbe:
            #NOTE(portdirect): use tcpSocket check as HTTP will return 401
            tcpSocket:
              port: 8778
            initialDelaySeconds: 15
            periodSeconds: 10
          livenessProbe:
            tcpSocket:
              port: 8778
            initialDelaySeconds: 50
            periodSeconds: 10
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: wsgi-nova
              mountPath: /var/www/cgi-bin/nova
            - name: nova-bin
              mountPath: /tmp/nova-placement-api.sh
              subPath: nova-placement-api.sh
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/nova.conf
              subPath: nova.conf
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/api-paste.ini
              subPath: api-paste.ini
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/policy.yaml
              subPath: policy.yaml
              readOnly: true
            - name: nova-etc
              mountPath: /etc/apache2/conf-enabled/wsgi-nova-placement.conf
              subPath: wsgi-nova-placement.conf
              readOnly: true
            - name: nova-etc
              mountPath: /etc/apache2/conf-enabled/security.conf
              subPath: security.conf
              readOnly: true

      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: wsgi-nova
          emptyDir: {}
        - name: nova-bin
          configMap:
            name: nova-bin
            defaultMode: 0555
        - name: nova-etc
          secret:
            secretName: nova-etc
            defaultMode: 0444

