---
# Source: nova/templates/deployment-novncproxy.yaml


---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: nova-novncproxy
  namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: release-name-nova-novncproxy
  namespace: openstack
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: release-name-openstack-nova-novncproxy
subjects:
  - kind: ServiceAccount
    name: nova-novncproxy
    namespace: openstack
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: release-name-openstack-nova-novncproxy
  namespace: openstack
rules:
  - apiGroups:
      - ""
      - extensions
      - batch
      - apps
    verbs:
      - get
      - list
    resources:
      - services
      - endpoints
      - jobs
      - pods
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nova-novncproxy
  annotations:
    "openstackhelm.openstack.org/release_uuid": ""
  labels:
    release_group: release-name
    application: nova
    component: novnc-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      release_group: release-name
      application: nova
      component: novnc-proxy
  revisionHistoryLimit: 3
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 1
      maxSurge: 3
  template:
    metadata:
      labels:
        release_group: release-name
        application: nova
        component: novnc-proxy
      annotations:
        "openstackhelm.openstack.org/release_uuid": ""
        configmap-bin-hash: "86616d85a7e726a16bc68931e0e2773ba86ae9be6058ec92db7d613dd4f2f1eb"
        configmap-etc-hash: "f99cc432cbe36c74dc6c48c6ec3be9040bec41a4baf5f24d1ccbb200d3ecf09c"
        
    spec:
      serviceAccountName: nova-novncproxy
      securityContext:
        runAsUser: 42424
        runAsUser: 42424
        
      affinity:
        
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
          - podAffinityTerm:
              labelSelector:
                matchExpressions:
                  - key: release_group
                    operator: In
                    values:
                    - release-name
                  - key: application
                    operator: In
                    values:
                    - nova
                  - key: component
                    operator: In
                    values:
                    - novnc-proxy
                  
              topologyKey: kubernetes.io/hostname
            weight: 10
      nodeSelector:
        openstack-control-plane: enabled
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      initContainers:
        
        - name: init
          image: "quay.io/airshipit/kubernetes-entrypoint:v1.0.0"
          imagePullPolicy: IfNotPresent  
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 65534
            
          env:
            - name: POD_NAME
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.name
            - name: NAMESPACE
              valueFrom:
                fieldRef:
                  apiVersion: v1
                  fieldPath: metadata.namespace
            - name: INTERFACE_NAME
              value: eth0
            - name: PATH
              value: /usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/
            - name: DEPENDENCY_SERVICE
              value: "openstack:mariadb"
            - name: DEPENDENCY_JOBS
              value: "nova-db-sync"
            - name: DEPENDENCY_DAEMONSET
              value: ""
            - name: DEPENDENCY_CONTAINER
              value: ""
            - name: DEPENDENCY_POD_JSON
              value: ""
            - name: DEPENDENCY_CUSTOM_RESOURCE
              value: ""
          command:
            - kubernetes-entrypoint
          volumeMounts:
            null
            
        - name: nova-novncproxy-init
          image: "docker.io/openstackhelm/nova:stein-ubuntu_bionic"
          imagePullPolicy: IfNotPresent
          
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            
          command:
            - /tmp/nova-console-proxy-init.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: nova-bin
              mountPath: /tmp/nova-console-proxy-init.sh
              subPath: nova-console-proxy-init.sh
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/nova.conf
              subPath: nova.conf
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: pod-shared
              mountPath: /tmp/pod-shared
        - name: nova-novncproxy-init-assets
          image: "docker.io/kolla/ubuntu-source-nova-novncproxy:ocata"
          imagePullPolicy: IfNotPresent
          
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            
          command:
            - /tmp/nova-console-proxy-init-assets.sh
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: nova-bin
              mountPath: /tmp/nova-console-proxy-init-assets.sh
              subPath: nova-console-proxy-init-assets.sh
              readOnly: true
            - name: pod-usr-share-novnc
              mountPath: /tmp/usr/share/novnc
      containers:
        - name: nova-novncproxy
          image: "docker.io/openstackhelm/nova:stein-ubuntu_bionic"
          imagePullPolicy: IfNotPresent
          
          
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            
          readinessProbe:
            tcpSocket:
              port: 6080
            initialDelaySeconds: 30
          livenessProbe:
            tcpSocket:
              port: 6080
            initialDelaySeconds: 30
          command:
            - /tmp/nova-console-proxy.sh
          ports:
            - name: n-novnc
              containerPort: 6080
          volumeMounts:
            - name: pod-tmp
              mountPath: /tmp
            - name: nova-bin
              mountPath: /tmp/nova-console-proxy.sh
              subPath: nova-console-proxy.sh
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/nova.conf
              subPath: nova.conf
              readOnly: true
            - name: nova-etc
              mountPath: /etc/nova/logging.conf
              subPath: logging.conf
              readOnly: true
            - name: pod-usr-share-novnc
              mountPath: /usr/share/novnc
              readOnly: true
            - name: pod-shared
              mountPath: /tmp/pod-shared

      volumes:
        - name: pod-tmp
          emptyDir: {}
        - name: nova-bin
          configMap:
            name: nova-bin
            defaultMode: 0555
        - name: nova-etc
          secret:
            secretName: nova-etc
            defaultMode: 0444
        - name: pod-usr-share-novnc
          emptyDir: {}
        - name: pod-shared
          emptyDir: {}

