---
# Source: nova/templates/pdb-osapi.yaml

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: nova-api-osapi
spec:
  minAvailable: 0
  selector:
    matchLabels:
      release_group: release-name
      application: nova
      component: os-api
