---
# Source: nova/templates/service-metadata.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: nova-metadata
spec:
  ports:
  - name: n-meta
    port: 8775
    
  selector:
    release_group: release-name
    application: nova
    component: metadata
  
