---
# Source: nova/templates/service-novncproxy.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: nova-novncproxy
spec:
  ports:
  - name: n-novnc
    port: 6080
    
  selector:
    release_group: release-name
    application: nova
    component: novnc-proxy
  
