---
# Source: mariadb/templates/pdb-mariadb.yaml

---
apiVersion: policy/v1beta1
kind: PodDisruptionBudget
metadata:
  name: mariadb-server
spec:
  minAvailable: 0
  selector:
    matchLabels:
      release_group: release-name
      application: mariadb
      component: server
