---
# Source: mariadb/templates/service.yaml

---
apiVersion: v1
kind: Service
metadata:
  name: mariadb-server
spec:
  ports:
    - name: mysql
      port: 3306
  selector:
    release_group: release-name
    application: mariadb
    component: server
